// suppliers/sanmar/color-hex-map.js
//
// SanMar Canada doesn't expose colour hex codes on any of its APIs:
//   - Bulk Data 1.0     returns `swatchColor` as a name only.
//   - Product Data 2.0  returns a single DEFAULT part with hex="NA".
//   - Media Content 1.2 returns `color` as a name, no hex field in schema.
//
// The storefront needs real dots, though, so we keep a hand-curated map
// keyed on the lowercased colour name we receive in `swatchColor`. Match
// is case-insensitive and trimmed; anything unmatched leaves color_hex
// NULL and the UI falls back to a grey circle.
//
// Coverage goal: every colour currently in supplier_variant should hit.
// Run `SELECT DISTINCT color_name FROM supplier_variant WHERE color_hex IS
// NULL ORDER BY color_name` after each ingest to find gaps — add rows to
// MAP, redeploy, hit POST /api/suppliers/sanmar/apply-color-hex to backfill.
//
// Keep keys lowercase, no punctuation variation beyond what SanMar sends.
// If SanMar changes a name (e.g. "Athletic Heather" → "Athletic Hthr") the
// old key can stay — it just won't match new rows.

const MAP = {
  // ── neutrals ────────────────────────────────────────────────────────
  'black':                 '#000000',
  'jet black':             '#0A0A0A',
  'true black':            '#000000',
  'white':                 '#FFFFFF',
  'off white':             '#F8F4E9',
  'natural':               '#E8DDBC',
  'ivory':                 '#FFFFF0',
  'cream':                 '#F5F0E1',
  'bone':                  '#E3DAC9',
  'khaki':                 '#B7A98B',
  'stone':                 '#8F826B',
  'sand':                  '#C2B280',
  'tan':                   '#AD9968',
  'beige':                 '#D9C29A',
  'camel':                 '#C19A6B',
  'coyote':                '#81613C',
  'brown':                 '#5C3A21',
  'dark chocolate':        '#3A2416',
  'chocolate':             '#4A2C1A',
  'espresso':              '#3C2A21',
  'mocha':                 '#7A5A3D',

  // ── greys ───────────────────────────────────────────────────────────
  'grey':                  '#808080',
  'gray':                  '#808080',
  'dark grey':             '#4A4A4A',
  'dark gray':             '#4A4A4A',
  'light grey':            '#B6B6B6',
  'light gray':            '#B6B6B6',
  'athletic heather':      '#A7A9AC',
  'heather grey':          '#A7A9AC',
  'heather gray':          '#A7A9AC',
  'sport grey':            '#9EA2A2',
  'sport gray':            '#9EA2A2',
  'ash':                   '#B2BEB5',
  'ash grey':              '#B2BEB5',
  'silver':                '#C0C0C0',
  'fog':                   '#BFC1C2',
  'smoke':                 '#848482',
  'steel':                 '#6D7278',
  'steel grey':            '#6D7278',
  'charcoal':              '#36454F',
  'charcoal heather':      '#4C5257',
  'dark heather':          '#4A4A4A',
  'graphite':              '#383E42',
  'graphite heather':      '#474B4E',
  'gravel':                '#707070',
  'coal':                  '#2B2B2B',
  'iron grey':              '#484A51',
  'iron gray':             '#484A51',

  // ── reds / pinks ────────────────────────────────────────────────────
  'red':                   '#D52B1E',
  'true red':              '#D52B1E',
  'classic red':           '#B11F24',
  'cardinal':              '#9E1B32',
  'cardinal red':          '#9E1B32',
  'deep red':              '#7B1113',
  'brick':                 '#B22222',
  'rust':                  '#B7410E',
  'burgundy':              '#800020',
  'maroon':                '#7C1F2C',
  'wine':                  '#722F37',
  'cherry':                '#CC2936',
  'heather red':           '#C04953',
  'pink':                  '#FF80AB',
  'light pink':            '#F4C2C2',
  'hot pink':              '#FF1493',
  'raspberry':             '#B3446C',
  'fuchsia':               '#C154C1',
  'coral':                 '#FF7F50',
  'salmon':                '#FA8072',
  'flamingo':              '#FC8EAC',
  'neon pink':             '#FF6EC7',

  // ── oranges / yellows ───────────────────────────────────────────────
  'orange':                '#E87722',
  'texas orange':          '#BF5700',
  'deep orange':           '#C04000',
  'burnt orange':          '#CC5500',
  'safety orange':         '#FF6600',
  'neon orange':           '#FF8C00',
  'mustard':               '#E1AD01',
  'gold':                  '#D4AF37',
  'old gold':              '#B39700',
  'vegas gold':            '#C5B358',
  'yellow':                '#FFD100',
  'athletic gold':         '#FFB81C',
  'maize':                 '#FFCC00',
  'bright yellow':         '#FFE600',
  'safety yellow':         '#F5E400',
  'neon yellow':           '#DFFF00',

  // ── greens ──────────────────────────────────────────────────────────
  'green':                 '#2E7D32',
  'kelly green':           '#4CBB17',
  'kelly':                 '#4CBB17',
  'hunter green':          '#355E3B',
  'hunter':                '#355E3B',
  'forest green':          '#228B22',
  'forest':                '#228B22',
  'lime':                  '#C0E200',
  'neon green':            '#39FF14',
  'safety green':          '#C7E400',
  'olive':                 '#708238',
  'olive drab':            '#6B8E23',
  'loden':                 '#4C5D3A',
  'military green':        '#4B5320',
  'army':                  '#4B5320',
  'army green':            '#4B5320',
  'dark green':            '#1E4D2B',
  'sage':                  '#9CAF88',
  'mint':                  '#B8E0D2',
  'teal':                  '#008080',
  'dark teal':             '#014D4E',
  'emerald':               '#046307',
  'heather forest':        '#3F6B48',
  'heather kelly':         '#6CAF5F',
  'heather military':      '#5C6D3E',

  // ── blues ───────────────────────────────────────────────────────────
  'blue':                  '#0F4C81',
  'royal':                 '#1D3FA5',
  'royal blue':            '#1D3FA5',
  'true royal':            '#1D3FA5',
  'deep royal':            '#162D6A',
  'navy':                  '#1B1F3A',
  'true navy':             '#1B1F3A',
  'classic navy':          '#1B1F3A',
  'dark navy':             '#0F1330',
  'light blue':            '#ADD8E6',
  'sky blue':              '#87CEEB',
  'columbia blue':         '#9BCBEB',
  'carolina blue':         '#4B9CD3',
  'light royal':           '#4169E1',
  'turquoise':             '#30D5C8',
  'aqua':                  '#00FFFF',
  'caribbean blue':        '#1CADC6',
  'atlantic blue':         '#264E70',
  'steel blue':            '#4682B4',
  'slate':                 '#6A7B8C',
  'slate blue':            '#6A5ACD',
  'heather navy':          '#3F4A6B',
  'heather royal':         '#4F6BB2',
  'heather columbia blue': '#6FA5C8',
  'indigo':                '#4B0082',

  // ── purples ─────────────────────────────────────────────────────────
  'purple':                '#5A2D82',
  'deep purple':           '#3A1862',
  'team purple':           '#5E2C8E',
  'violet':                '#7F00FF',
  'lavender':              '#E6E6FA',
  'orchid':                '#DA70D6',
  'heather purple':        '#6F5499',

  // ── SanMar/ATC specialties ──────────────────────────────────────────
  'realtree xtra':         '#3F4F2F',
  'realtree edge':          '#5C6141',
  'realtree ap':           '#4A5D32',
  'mossy oak':             '#3B4423',
  'camo':                  '#4E5B31',
  'desert camo':           '#C3B091',
  'digital camo':          '#5B6D4C',
  'woodland camo':         '#4E5B31',
  'blaze orange':          '#FF5F00',
  'copper':                '#B87333',
  'rose gold':             '#B76E79',
  'berry':                 '#7E2F4C',
  'plum':                  '#8E4585',
  'eggplant':              '#614051',
  'pine':                  '#01796F',
  'spruce':                '#425947',
  'evergreen':             '#05472A',

  // ── heather "x" patterns we see a lot ───────────────────────────────
  'heather charcoal':      '#4C5257',
  'heather black':         '#2B2B2B',
  'heather white':         '#E8E8E8',
  'heather athletic grey': '#A7A9AC',
  'heather athletic gray': '#A7A9AC',

  // -- reversed "heather X" <-> "X heather" synonyms --------------------
  // SanMar uses both orderings; keep both keys pointing at the same hex.
  'black heather':         '#2B2B2B',
  'white heather':         '#E8E8E8',
  'grey heather':          '#A7A9AC',
  'gray heather':          '#A7A9AC',
  'navy heather':          '#3F4A6B',
  'royal heather':         '#4F6BB2',
  'red heather':           '#C04953',
  'purple heather':        '#6F5499',
  'forest heather':        '#3F6B48',
  'military heather':      '#5C6D3E',
  'indigo heather':        '#5F6AA8',
  'irish green heather':   '#4D8F5C',
  'maroon heather':        '#8F3C48',
  'orange heather':        '#E89550',

  // -- neutrals (extended) ----------------------------------------------
  'true white':            '#FFFFFF',
  'bright white':          '#FFFFFF',
  'deep black':            '#000000',
  'soft black':            '#0A0A0A',
  'space black':           '#000000',
  'blacktop':              '#1C1C1C',
  'caviar':                '#1A1A1A',
  'caviar black':          '#0A0A0A',
  'faded black':           '#303030',
  'onyx':                  '#353839',
  'onyx frost':            '#575A5D',
  'stealth':               '#2F2F2F',
  'pepper':                '#3A3A3A',
  'chrome':                '#C0C0C0',
  'aluminum grey':         '#A5ACAF',
  'aluminum gray':         '#A5ACAF',
  'sandstone':             '#C2A482',
  'sahara':                '#C2B280',
  'timber tan':            '#C19A6B',
  'light stone':           '#A99879',
  'dark sand':             '#A08E6F',
  'light khaki':           '#C3B091',
  'dark khaki':            '#8F7E4F',
  'bark':                  '#4A3728',
  'bay':                   '#80461B',
  'saddle':                '#8B4513',
  'carhartt brown':        '#61422A',
  'coffee bean':           '#3C2A21',
  'coffee brown':          '#4A3728',
  'chocolate brown':       '#4A2C1A',
  'dark brown':            '#3B2820',
  'dark chocolate brown':  '#2F1E14',
  'duck brown':            '#5A3E2B',
  'woodland brown':        '#5C4033',
  'caramel':               '#AF6F2B',
  'canyon drift':          '#B8936F',
  'antique white':         '#FAEBD7',
  'vintage white':         '#F3E9D2',
  'white sand':            '#E8DDBC',
  'winter white':          '#F5F0E1',
  'dawn':                  '#D7C6B8',

  // -- greys (extended) -------------------------------------------------
  'anthracite':            '#3D3E3F',
  'anthracite heather':    '#4A4B4D',
  'asphalt':               '#40434E',
  'asphalt grey':          '#40434E',
  'asphalt gray':          '#40434E',
  'asphalt heather':       '#4F535E',
  'coal grey':             '#2B2B2B',
  'coal gray':             '#2B2B2B',
  'athletic grey':         '#9EA2A2',
  'athletic gray':         '#9EA2A2',
  'athletic oxford':       '#3A3B3C',
  'charcoal grey':         '#36454F',
  'charcoal gray':         '#36454F',
  'charcoal heather grey': '#4C5257',
  'charcoal heather gray': '#4C5257',
  'charcoal triblend':     '#484D52',
  'charcoal dynamic':      '#3F4448',
  'black caviar heather':  '#252525',
  'dark grey heather':     '#4A4A4A',
  'dark gray heather':     '#4A4A4A',
  'dark heather grey':     '#4A4A4A',
  'dark heather gray':     '#4A4A4A',
  'deep heather':          '#3E3E3E',
  'medium grey':           '#808080',
  'medium gray':           '#808080',
  'medium grey heather':   '#9A9DA0',
  'medium gray heather':   '#9A9DA0',
  'mid grey':              '#808080',
  'mid gray':              '#808080',
  'cool grey':             '#8C92AC',
  'cool gray':             '#8C92AC',
  'storm grey':            '#4A4E54',
  'storm gray':            '#4A4E54',
  'iron gate':             '#3A3A3A',
  'slate grey':            '#708090',
  'slate gray':            '#708090',
  'smoked pearl':          '#A6A5A1',
  'platinum grey':         '#B9BCBF',
  'platinum gray':         '#B9BCBF',
  'monument':              '#686A6E',
  'concrete':              '#95978C',
  'grey concrete':         '#95978C',
  'gray concrete':         '#95978C',
  'canteen grey':          '#797C7F',
  'canteen gray':          '#797C7F',
  'terrain grey':          '#5C5E5E',
  'terrain gray':          '#5C5E5E',
  'quiet shade':           '#6D6E70',
  'grey steel':            '#646972',
  'gray steel':            '#646972',
  'faded grey':            '#A0A0A0',
  'faded gray':            '#A0A0A0',
  'grey frost':            '#C9CDD0',
  'gray frost':            '#C9CDD0',
  'grey shadow':           '#7D7D7D',
  'gray shadow':           '#7D7D7D',
  'grey triblend':         '#A7A9AC',
  'gray triblend':         '#A7A9AC',
  'caviar grey':           '#3C3C3C',
  'caviar gray':           '#3C3C3C',
  'caviar heather':        '#474747',
  'heather':               '#A7A9AC',
  'heather dark grey':     '#4A4A4A',
  'heather dark gray':     '#4A4A4A',
  'highrise heather':      '#BFC2C4',
  'light heather':         '#C8CACC',
  'glacier grey':          '#C8CED3',
  'glacier gray':          '#C8CED3',
  'glacier heather':       '#B8C0C5',
  'granite heather':       '#7E8286',
  'castlerock heather':    '#5C6267',
  'pearl grey heather':    '#CACDD0',
  'pearl gray heather':    '#CACDD0',
  'sport heather grey':    '#A7A9AC',
  'sport heather gray':    '#A7A9AC',
  'white fleck triblend':  '#DCDCDC',
  'oxford blue':           '#002147',

  // -- reds / pinks (extended) ------------------------------------------
  'scarlet':               '#D52B1E',
  'scarlet red':           '#D52B1E',
  'scarlet frost':         '#E9756C',
  'rich red':              '#B11F24',
  'chili pepper':          '#C21807',
  'caldera red':           '#B33A3A',
  'fireball red':          '#CE2029',
  'jester red':            '#8C1717',
  'red jasper':            '#B73C3C',
  'salsa red':             '#C7363A',
  'signal red':            '#BF1932',
  'sport red':             '#CE2029',
  'gym red':               '#CE2029',
  'university red':        '#C81D25',
  'pro red':               '#CE2029',
  'revolution red':        '#C31E26',
  'ripped red':            '#C62828',
  'rise up red':           '#C02020',
  'red triblend':          '#C04953',
  'blush red':             '#C5697E',
  'rosewood':              '#65000B',
  'sangria':               '#92000A',
  'very berry':            '#8E3A59',
  'cardinal heather':      '#9E1B32',
  'candy pink':            '#E4717A',
  'hibiscus':              '#B43757',
  'heliconia':             '#E6597B',
  'pink orchid':           '#D580B0',
  'pink punch':            '#F06292',
  'pink raspberry':        '#B3446C',
  'pink camo':             '#D98BA0',
  'dark fuchsia':          '#A12470',
  'raspberry heather':     '#AD5275',
  'wild raspberry':        '#B03060',
  'dusty rose':            '#DCAE96',
  'pale blush':            '#F4C2C2',
  'blossom':               '#F6B4C8',
  'sorbet':                '#F5A6A3',
  'tropical pink':         '#F48CA4',
  'extreme pink':          '#FF1493',
  'prism red':             '#D52B1E',

  // -- oranges / yellows (extended) -------------------------------------
  'cayenne orange':        '#D94E1F',
  'extreme orange':        '#FF4500',
  'orange burst':          '#E8792E',
  'bright orange':         '#FF7518',
  'brilliant orange':      '#FF6F00',
  'deep orange heather':   '#D57242',
  'neon orange heather':   '#FFA54F',
  'prism orange':          '#E87722',
  'pumpkin':               '#FF7518',
  'yam':                   '#BF5B36',
  'terracotta':            '#E2725B',
  'butter':                '#FFE680',
  'banana':                '#FFE135',
  'daisy':                 '#FFEB3B',
  'pace yellow':           '#FFE600',
  'nitro yellow':          '#FDE047',
  'goldenrod yellow':      '#DAA520',
  'citron':                '#DFFF00',
  'extra red':             '#D52B1E',
  'extra yellow':          '#F5E400',
  'extreme yellow':        '#F5E400',
  'yield yellow':          '#FFE600',
  'tnf yellow':            '#F9D71C',

  // -- greens (extended) ------------------------------------------------
  'alloy green':           '#5E6F3E',
  'astro green':           '#1FA251',
  'athletic green':        '#2E7D32',
  'balsam green':          '#2F5233',
  'burnt olive green':     '#6A6337',
  'olive green':           '#708238',
  'olive you green':       '#748A3E',
  'faded olive':           '#817B52',
  'faded tan':             '#BDB76B',
  'fatigue green':         '#4B5320',
  'military camo':         '#4E5B31',
  'military frost':        '#7B8A5A',
  'matcha green':          '#A4C639',
  'chive green':           '#6F7A35',
  'clover green':          '#4CBB17',
  'court green':           '#3CB371',
  'cypress':               '#3A533E',
  'gorge green':           '#2A4D3E',
  'gridiron green':        '#3F6B48',
  'green oasis':           '#3AA957',
  'fuel green':            '#1FA251',
  'fresh green':           '#3CB371',
  'hedge green':           '#3A6E3A',
  'irish green':           '#009A44',
  'laurel green':          '#A9BA9D',
  'light green':           '#90EE90',
  'mineral green':         '#3B7A6A',
  'moss':                  '#8A9A5B',
  'taupe green':           '#6F6A4D',
  'thyme':                 '#85A01F',
  'true celadon':          '#ACE1AF',
  'turf green heather':    '#5C8F5C',
  'vine green':            '#3E6B34',
  'vibrant green':         '#42C15A',
  'wasabe':                '#788A35',
  'wintergreen':           '#5C8F5C',
  'honeydew':              '#C3E0A3',
  'seafoam':               '#93E9BE',
  'teal heather':          '#3F8A8A',
  'forest green heather':  '#3F6B48',

  // -- blues (extended) -------------------------------------------------
  'aquatic blue':          '#4FA3CD',
  'arctic blue':           '#7EC8E3',
  'atomic blue':           '#1B5E9A',
  'authentic blue':        '#1D3FA5',
  'azure blue':            '#007FFF',
  'beacon blue':           '#2E5C87',
  'blue agave':            '#4F97A3',
  'blue atoll':            '#00B4D8',
  'blue enamel':           '#1F4E79',
  'blue jean':             '#5A7E95',
  'blue lake':             '#2A6F97',
  'blue mist':             '#B1CCDC',
  'blue ribbon':           '#1F4E79',
  'blue spruce':           '#3B6D6B',
  'blueberry pancake':     '#3E4A78',
  'blueprint':             '#2E5C87',
  'blueprint heather':     '#4E6F91',
  'blue surf':             '#4A90B8',
  'blue steel':            '#3E5C76',
  'blue wake':             '#2B4E72',
  'blue wake heather':     '#4A6888',
  'bolt blue':             '#1A5AA0',
  'bright aqua':           '#00B6D7',
  'bright blue':           '#0088CC',
  'brilliant blue':        '#0047AB',
  'brisk blue':            '#3A75C4',
  'chambray':              '#9FB4CC',
  'city blue':             '#2A6F97',
  'cobalt blue':           '#0047AB',
  'cobalt heather':        '#3F5B8A',
  'college navy':          '#162D6A',
  'deep blue':             '#0F4C81',
  'deep navy':             '#0F1330',
  'deep sea blue':         '#014D4E',
  'deep sea green':        '#1F4E3D',
  'diesel grey':           '#3D4145',
  'diesel gray':           '#3D4145',
  'denim':                 '#5A7E95',
  'electric blue':         '#3A75C4',
  'flo blue':              '#1F4E79',
  'game royal':            '#1D3FA5',
  'game royal heather':    '#4F6BB2',
  'gear grey':             '#5B5F63',
  'gear gray':             '#5B5F63',
  'glacier blue':          '#B8D8E3',
  'imperial blue':         '#00416A',
  'lapis':                 '#26619C',
  'lapis blue':            '#26619C',
  'lapis blue frost':      '#5586B3',
  'magnetic blue':         '#1B5AA7',
  'marine':                '#1B1F3A',
  'mediterranean blue':    '#1F6FB2',
  'medium blue':           '#3A75C4',
  'midnight':              '#191970',
  'midnight blue':         '#0F1330',
  'midnight navy':         '#0F1330',
  'moonlight blue':        '#4874B1',
  'navy camo':             '#0F1330',
  'navy frost':            '#4C5877',
  'navy triblend':         '#3F4A6B',
  'neon blue':             '#1F51FF',
  'neon blue heather':     '#4E74B4',
  'neon lime':             '#BFFF00',
  'neptune blue':          '#4B9CD3',
  'night sky navy':        '#0F1330',
  'old royal':             '#1D3FA5',
  'palace blue':           '#4169A0',
  'peacoat navy':          '#1B1F35',
  'peak blue':             '#3A75C4',
  'pearl blue':            '#AEC9DB',
  'petrol':                '#1F4E5F',
  'prism navy':            '#1B1F3A',
  'prism royal':           '#1D3FA5',
  'provence blue':         '#5D8AA8',
  'regatta blue':          '#1D3FA5',
  'rush blue':             '#1A5AA0',
  'royal triblend':        '#4F6BB2',
  'sapphire':              '#0F52BA',
  'sky':                   '#87CEEB',
  'surf the web':          '#0053A0',
  'true blue':             '#1D3FA5',
  'tnf blue':              '#1B1F3A',
  'tradewinds':            '#6B9AA0',
  'tropic blue':           '#3A75C4',
  'urban navy':            '#1B1F3A',
  'valor blue':            '#1B4B8A',
  'varsity royal':         '#1D3FA5',
  'true royal dynamic':    '#1D3FA5',

  // -- purples / miscellaneous (extended) -------------------------------
  'amethyst':              '#9966CC',
  'aubergine purple':      '#614051',
  'grape harvest':         '#6B2C5F',
  'huckleberry':           '#4D4078',
  'purple haze':           '#8E4585',
  'purple luxe':           '#5C3482',
  'black iris blue':       '#353839',
  'dusk':                  '#7E7EB8',

  // -- SanMar sub-brand series -----------------------------------------
  // Earth series (eco line) -- mapped to sensible base colours
  'earth black':           '#1E1E1E',
  'earth bone':            '#E3DAC9',
  'earth caramel':         '#AF6F2B',
  'earth cypress':         '#3A533E',
  'earth dove':            '#9E9E9E',
  'earth eggplant':        '#614051',
  'earth harbour blue':    '#355873',
  'earth military':        '#4B5320',
  'earth navy':            '#1B1F3A',
  'earth orange':          '#D95D21',
  'earth pewter':          '#8B8983',
  'earth red':             '#B53030',
  'earth rose':            '#C4727E',
  'earth sand':            '#C2B280',
  'earth stone blue':      '#6C8DAA',

  // Flag series (ATC flag line)
  'flag black':            '#000000',
  'flag camo':             '#4E5B31',
  'flag charcoal':         '#36454F',
  'flag dark green':       '#1E4D2B',
  'flag dark navy':        '#0F1330',
  'flag deep navy':        '#0F1330',
  'flag graphite':         '#383E42',
  'flag grey':             '#808080',
  'flag gray':             '#808080',
  'flag navy':             '#1B1F3A',
  'flag royal':            '#1D3FA5',
  'flag scarlet':          '#D52B1E',
  'flag scarlet red':      '#D52B1E',
  'flag white':            '#FFFFFF',

  // Prism series
  'prism black':           '#000000',

  // Team series
  'team anthracite':       '#3D3E3F',
  'team black':            '#000000',
  'team charcoal':         '#36454F',
  'team dark heather':     '#4A4A4A',
  'team forest green':     '#228B22',
  'team gold':             '#D4AF37',
  'team navy':             '#1B1F3A',
  'team red':              '#D52B1E',
  'team royal':            '#1D3FA5',
  'team scarlet':          '#D52B1E',

  // Dynamic finishing series
  'black dynamic':         '#000000',

  // Camo variants (MultiCam / Realtree / generic)
  'multicam':              '#8A7F60',
  'multicam black':        '#2B2B2B',
  'black camo':            '#2A2B26',
  'grey camo':             '#6E7179',
  'gray camo':             '#6E7179',

  // Lime / neon
  'lime shock':            '#BFFF00',

  // Oatmeal
  'oatmeal heather':       '#D6CCB2',
};

/**
 * Normalize a SanMar colour name into the form used as a MAP key.
 *
 * Handles the common noise SanMar feeds us:
 *   - ®/™/© trademark symbols          ("Realtree Xtra®"        → "realtree xtra")
 *   - parenthetical suffixes           ("Navy (Heather)"        → "navy")
 *   - asterisk decorators              ("Athletic Heather**"    → "athletic heather")
 *   - caret prefixes on safety colours ("^Safety Green"         → "safety green")
 *   - inseam suffixes on pants/shorts  ("Black Inseam 30\""     → "black")
 *   - leading/trailing + repeated ws   ("Athletic  Heather"     → "athletic heather")
 *   - case                             ("BLACK"                 → "black")
 *
 * Exported so the ingest/backfill paths can use the same canonical form.
 */
function normalizeColorName(colorName) {
  if (colorName == null) return '';
  return String(colorName)
    .replace(/[®™©]/g, '')                    // trademark symbols
    .replace(/\s*\([^)]*\)\s*/g, ' ')         // parenthetical suffixes
    .replace(/\*+/g, '')                      // asterisks anywhere
    .replace(/^\^+/, '')                      // leading carets
    .replace(/\s+inseam\s+\d+"?/gi, '')       // "Inseam 30\"" size suffix
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ');
}

/**
 * Look up a hex code for a SanMar colour name.
 *
 * Match is case-insensitive, whitespace-trimmed, and aggressively normalized
 * (see normalizeColorName). For two-tone names ("Black/White", "Navy/Gold")
 * we fall back to the body colour (everything before the first slash), which
 * is SanMar's convention. Returns null for unknown names — caller writes
 * NULL and the UI shows a grey circle.
 *
 * @param {string|null|undefined} colorName  e.g. "Athletic Heather", "Realtree Xtra®", "Black/White"
 * @returns {string|null}  "#RRGGBB" or null
 */
function lookupHex(colorName) {
  const key = normalizeColorName(colorName);
  if (!key) return null;

  // Direct hit on the full (normalized) name
  if (MAP[key]) return MAP[key];

  // Two-tone fallback: use body colour only
  if (key.includes('/')) {
    const body = normalizeColorName(key.split('/')[0]);
    if (body && body !== key && MAP[body]) return MAP[body];
  }

  return null;
}

module.exports = { lookupHex, normalizeColorName, MAP };
