-- setup-auth.sql — DEPRECATED
--
-- This script was used once, against the old Azure SQL `Employee` table, to
-- add `PasswordHash`, `Role`, and `Active` columns. The Railway Postgres
-- `employees` table already has those columns built in (password_hash,
-- role, active) — no schema bootstrap needed anymore.
--
-- To (re)set passwords on Railway:   node db/set-passwords.js
--
-- Safe to delete this file.
